#!/usr/bin/env ruby

Dir.glob('*.yml') do |f|
  base = File.basename(f, File.extname(f)).chomp
  puts "[Executing] $ mustache #{base}.yml itg.flat.mustache >! itg.flat.#{base}.sublime-theme"
  %x[ bundle exec mustache #{base}.yml itg.flat.mustache >! itg.flat.#{base}.sublime-theme ]
end